dist: xenial
language: php

services:
  - mysql
  - postgresql
  - memcached
  - redis

php:
  - 7.2
  - 7.3
  - 7.4

env:
  jobs:
    - DB=mysql
      COMPOSER=1
    - DB=mysql
      COMPOSER=2
    - DB=sqlite
      COMPOSER=1
    - DB=pgsql
      COMPOSER=1
    - DB=memory
      COMPOSER=1

jobs:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Force use of Composer 1x or 2.x
  - composer self-update --$COMPOSER
  - composer config -g github-oauth.github.com "$TOKEN"
  # copy sprinkles.json
  - cp app/sprinkles.example.json app/sprinkles.json
  # set up db
  - bash build/before_install.sh $DB
  # update node
  - nvm install 10.12.0
  # Install Redis and Memcached
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "\n" | pecl install -f redis

before_script:
  # install deps and UF
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --no-interaction
  - php bakery debug
  - php bakery build-assets
  - php bakery migrate

script:
  # run unit tests
  - app/vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat app/log/userfrosting.log
